apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    telemetry:
      enabled: false
  meshConfig:
    # This enables viewing handshake statistics
    defaultConfig:
      proxyStatsMatcher:
        inclusionPrefixes:
          - "listener"
