# Data: latency
telemetry_mode: "none"
conn:
  - 2
qps:
  - 10

duration: 120
perf_record: false
run_bothsidecar: false
run_serversidecar: false
run_clientsidecar: false
run_baseline: false

jitter: false

run_ingress: "https://istio-ingressgateway.istio-system.svc.cluster.local"
headers: "Host:fortioserver.fake-dns.org"
cacert: "/tmp/gateway-secret/tls.crt"

uniform: true
nocatchup: true
keepalive: true
connection_reuse: '1:60'
